targets:
  $default:
    builders:
      drift_dev:
        generate_for:
          - "lib/data/local/**"
        options:
          # compact_query_methods: true
          store_date_time_values_as_text: true
