name: fclash
description: A clash proxy fronted.
publish_to: 'none'
aversion: 1.4.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  kommon: ^0.4.0
  path: ^1.8.2
  path_provider: ^2.0.14
  tray_manager: ^0.2.0
  window_manager: ^0.3.2
  settings_ui: ^2.0.2
  launch_at_startup: ^0.2.2
  package_info_plus: ^3.1.2
  flutter_local_notifications: ^14.0.0+1
  ffigen: ^6.0.0
  proxy_manager: ^0.0.3
  clipboard: ^0.1.3
  url_launcher: 6.1.10
  icons_launcher: ^2.0.4
  system_proxy: ^0.1.0
  open_settings: ^2.0.2
  yaml: ^3.1.2
  yaml_writer: ^1.0.3
  flutter_svg: ^2.0.5
  go_router: ^7.0.0
  flex_color_scheme: ^7.0.5
  slang: ^3.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  slang_build_runner: ^3.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/tp/clash/
    - assets/images/

  fonts:
    - family: nssc
      fonts:
        - asset: fonts/NotoSansSC-Regular.otf

flutter_intl:
  enabled: true

ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'clash/libclash.h'